name: ci/cd

on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main, release/*]

jobs:
  build:
    name: Build on OpenJDK ${{ matrix.jdk_version }} / ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # JDK LTS: 8, 11, 17
        jdk_version: [8, 11, 17]
        os: [ubuntu-latest]

    container:
      image: clojure:openjdk-${{ matrix.jdk_version }}-tools-deps

    steps:
      - uses: actions/checkout@v4
      - name: Version
        run: clj --version
      - name: Prepare Deps
        run: clj -P
      - name: Test, Write POM, Build
        run: clj -T:build ci
