name: ci/cd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build on Temurin JDK ${{ matrix.jdk_version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk_version: [11, 17, 21, 25]

    container:
      image: clojure:temurin-${{ matrix.jdk_version }}-tools-deps

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure/.cpcache
          key: deps-${{ matrix.jdk_version }}-${{ hashFiles('deps.edn') }}
          restore-keys: deps-${{ matrix.jdk_version }}-

      - name: Version
        run: clojure --version

      - name: Resolve dependencies
        run: |
          echo "Resolving main dependencies..."
          clojure -P
          echo "Resolving lint and format dependencies..."
          clojure -P -M:lint:cljfmt
          echo "Resolving test dependencies..."
          clojure -P -X:test
          echo "Resolving build dependencies..."
          clojure -P -T:build

      - name: Format check
        run: clojure -M:cljfmt check src/ test/ dev/

      - name: Lint
        run: clojure -M:lint src/ test/ dev/

      - name: Test
        run: clojure -X:test

      - name: Build
        run: clojure -T:build jar
